# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackstart" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f9beff5ce26c9404259762e82788274d67fa7850851272f22fb4bc174587d45d"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a3d87bfd44fd07a221e6395f7c43c7cd500de25b8071291720bd7a8494db8b4"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21c20f71d2be5e9c55cec6a9f3706a824bc98a72859f7f4e77b0f90d2e708ae2"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00e2c7fa84bd656e46c18339115dc1d3cc0aa058a83abeb29f9754c43e68a15c"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stackstart"
  desc "Runtime-aware local dev orchestrator"
  homepage "https://github.com/orpic/stack-start"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackstart"

  # No zap stanza required

end
