# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackstart" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "348cc80887b819d921409965c7a778db5b875a7d14c2896464fdb410f7b7a4e4"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f447ca2b4198dfc8e5a852e6240314578be72a3021a7d13319bd0a50b420e08"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "750bef9969fe9dbbea3f9f0f8a5d57fe40751f9b541c3681350f093dbfd61047"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ca96af1399ec5c7a94889e842399d7cc6fde23f3e6fd041a7057a2a4f9a3f17"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stackstart"
  desc "Runtime-aware local dev orchestrator"
  homepage "https://github.com/orpic/stack-start"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackstart"

  # No zap stanza required

end
