# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackstart" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "4b5062b9c2f6a5b4000e43c2856ff0b5b9478a60d9c3b6996d4f4f4f22e4a680"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0480e365c164ac809c1e80c2b9375a3b318d8bbe86f347a79113fb9d533c466f"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a469dfd1cc33b903dc5308c16e5945b891d55b60d09b0a1c10f6cfb3afc7680b"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aef1ca12844086cc2db41a428cd3b9ba57b49925188ac078388faeb3b3b93ca9"
      url "https://github.com/orpic/stack-start/releases/download/v#{version}/stackstart_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stackstart"
  desc "Runtime-aware local dev orchestrator"
  homepage "https://github.com/orpic/stack-start"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackstart"

  # No zap stanza required

end
